### ISSUE TITLE
Library Appears to be missing Media Stop command

### ISSUE THREAD

**Issue by FabianKopp** [aevans1500/java-media-keys#1]
Appears to be missing:
VK_MEDIA_STOP
0xB2

**Comment by FabianKopp** [comment]
VK_MEDIA_STOP
0xB2

**Comment by nsnave** [comment]
When I originally created the library, I didn't need the Media Stop virtual key as play/pause worked for what I needed. 

I responded to [this StackOverflow post](https://stackoverflow.com/a/55321025/11039508) explaining how to format the code. Basically, if Media Stop is needed specifically, then add a new function to the .c and .h files changing `kbi.wVk` to equal `VK_MEDIA_STOP`. 

This [link](https://www3.ntu.edu.sg/home/ehchua/programming/java/JavaNativeInterface.html) is really helpful when it comes to creating the .dll file and setting up the JNI.

I'll update the source files in the repository to include Media Stop but it'll take a little longer to upload a new .dll as I've switched computers since last compiling the .dll currently uploaded.

**Comment by nsnave** [comment]
Okay, updating the .dll was easier than I thought. The new .dll and source files are all updated to reflect the change of adding the the Media Stop command. 

I created a backup folder with the old dll just in case something went wrong when I created the new dll. I tested it on my computer (64bit Windows 10) but I'm not sure about other Windows machines. Originally, the dll was compiled using GCC with MinGW but the new one I used GCC with POSIX so there might be slight compatibility issues but I don't think this will be a problem since no POSIX specific code was used. Regardless, the source files are correct.

Thanks for pointing this out; I had fun going back through this code lol.
